### ISSUE TITLE
About prerequisite of Veeam

### ISSUE THREAD

**Issue by laurentkr** [VeeamHub/grafana#17]
Hi,
We managed to use dashboard "veeam-enterprise_manager-grafana" on our system, we follow all instructions but we didn't received data on dashboard.

Problem can be link to our version of Veeam ?

Actually our version of Veeam is : Backup & Replication 11

**Comment by jorgedlcruz** [comment]
Hello, sorry it took me some time to reply. Did you manage to get it working? Ping me if not.

**Comment by jorgedlcruz** [comment]
Closing as no response
