### ISSUE TITLE
Panel plugin not found: grafana-worldmap-panel

### ISSUE THREAD

**Issue by ericlaiys** [VeeamHub/grafana#4]
Import the json into grafana 7.01

Error message displayed "Panel plugin not found: grafana-worldmap-panel" and "Panel plugin not found: grafana-piechart-panel"

Tested on VB for Azure

**Comment by jorgedlcruz** [comment]
Hello,
You will need to install both plugins on your Linux system with Grafana run the next
`grafana-cli plugins install grafana-worldmap-panel`
`grafana-cli plugins install grafana-piechart-panel`
`service grafana-server restart`

**Comment by ericlaiys** [comment]
sorry. found the problem. need to download an additional plugin

**Comment by ericlaiys** [comment]
> grafana-cli plugins install grafana-piechart-panel

Got it. Thanks
